### ISSUE TITLE
fuxictr_1.0.2中按FGCNN_avazu_x4_001的配置文件运行代码，AUC始终为0.5

### ISSUE THREAD

**Issue by discivigour** [openbenchmark/BARS#10]
您好！  我在使用fuxictr_1.0.2+BARS时，按FGCNN_avazu_x4_001的配置文件运行代码，AUC始终为0.5。将配置文件中的conv_batch_norm与dnn_batch_norm全部设置为false时才能运行出有效结果（库中原配置文件conv_batch_norm为true），这是为什么？
   或者将学习率由0.001调整到0.0001也能解决此问题

**Comment by xpai** [comment]
这个模型确实有这种情况，应该是模型没法收敛。解决办法一般是调小lr(5.e-4就ok)。最近又重新跑了一遍FGCNN_kkbox_x1时也是调小了lr的。
至于为什么我跑的时候没有出现你的情况，应该是机器不同参数初始化不同，所以有时候收敛了。你也可以换个seed 重新初始化试试。

**Comment by xpai** [comment]
应该是跑avazu_x4划分的时候，当时的设想是尽量跟论文一致，很多论文没有提到在DNN中使用BN，就统一设为false了。这样也许也许能够后来者一些提升的机会。

**Comment by discivigour** [comment]
> 应该是跑avazu_x4划分的时候，当时的设想是尽量跟论文一致，很多论文没有提到在DNN中使用BN，就统一设为false了。这样也许也许能够后来者一些提升的机会(即使这样提升好像也很难)。从avazu_x1划分开始，后来就是全调参了，bn是调过的。

谢谢解答！
