### ISSUE TITLE
parameter setting for BCEloss on yelp2018

### ISSUE THREAD

**Issue by junkangwu** [openbenchmark/BARS#11]
Hi, I came across CIKM2021-SimpleX: A Simple and Strong Baseline forCollaborative Filtering, Nice work!
However, in terms of Table 1, I could not reproduce the result of BCELoss on yelp2018, Looking forward to your help!
Thanks a lot @zhujiem @xpai

**Comment by xpai** [comment]
Hi，I remember that BCE Loss should work with large number of negative samples. Meanwhile，batch sum is more stable than batch mean loss. I shall post the config here by this week (struggle on the ctr task recently)
