### ISSUE TITLE
Taobao dataset result and config

### ISSUE THREAD

**Issue by W-lw** [openbenchmark/BARS#12]
Hello~ I find there are no dataset config files of Taobao dataset in the folder of benchmarks, would you provide them in a further version?

**Comment by xpai** [comment]
Thanks for questioning. The results of taobao dataset are somewhat counter-intuitive,  where DIN cannot bring any gains over DCN. We are trying to refine the sequence features in data to make it work. I hope the results can be available in two weeks.

**Comment by xpai** [comment]
Thanks for questioning. The results of taobao dataset are somewhat counter-intuitive,  where DIN cannot bring any gains over DCN. We are trying to refine the sequence features in data to make it work. I hope the results can be available in two weeks.

**Comment by xpai** [comment]
Sorry for the late updates: 
https://github.com/openbenchmark/BARS/tree/main/ctr_prediction/benchmarks/DIN
