### ISSUE TITLE
sequential models

### ISSUE THREAD

**Issue by chqiwang** [openbenchmark/BARS#13]
When will sequential models like din/dien to be evaluated on these public benchmarks? Do you have a plan?

**Comment by zhujiem** [comment]
Expected in this Sep.

**Comment by zhujiem** [comment]
Please see our recent updates:
https://github.com/openbenchmark/BARS/tree/main/ctr_prediction/benchmarks/DIN
https://github.com/openbenchmark/BARS/tree/main/ctr_prediction/benchmarks/DIEN
https://github.com/openbenchmark/BARS/tree/main/ctr_prediction/benchmarks/BST
