### ISSUE TITLE
Amazon-CDs/Movies/Beauty

### ISSUE THREAD

**Issue by MTandHJ** [openbenchmark/BARS#14]
Though BGCF KDD'20 provides the dataset splitting details, it is still hard to fully reproduce it (due to the lack of the random seed). Could you provide official links of AmazonCDs/Movies/Beauty_m1  to download?

Thanks.

**Comment by xpai** [comment]
https://mycuhk-my.sharepoint.com/:f:/g/personal/1155009459_link_cuhk_edu_hk/En7Zv-lX1MNOg_b1MtMomocBN1emvTz_316-eOhlSyMmlw?e=neUyK6

You can download at this link.
