### ISSUE TITLE
按照Running steps做的结果和README中的logs信息不一致

### ISSUE THREAD

**Issue by SSBCL-zjgsu** [openbenchmark/BARS#17]
您好，
在DCN_criteo_x4_001中，按照Running steps做出的结果是
"data_format": "csv",
"dataset_id": "criteo_x4_9ea3bdfc",
"model_id": "DCN_criteo_x4_012_dc8ab363",
"model_root": "./Criteo/DCN_criteo_x4_001/",
最终结果 logloss:0.437622 - AUC:0.814319

但README中的logs信息为
"data_format": "h5",
"dataset_id": "criteo_x4_5c863b0f",
"model_id": "DCN_criteo_x4_5c863b0f_012_56382345",
"model_root": "./Criteo/DCN_criteo/min10/",
最终结果 logloss: 0.437612 - AUC: 0.814437
且项目中没有找到README中包含的内容

@zhujiem @xpai 感谢解答！

**Comment by zhujiem** [comment]
在DCN_criteo_x4_001中，按照Running steps做出的结果是
"data_format": "csv",
"dataset_id": "criteo_x4_9ea3bdfc",
"model_id": "DCN_criteo_x4_012_dc8ab363",
"model_root": "./Criteo/DCN_criteo_x4_001/",
最终结果 logloss:0.437622 - AUC:0.814319
--------------------
请问这个结果是你自己重新跑的？

**Comment by SSBCL-zjgsu** [comment]
> ```
> 在DCN_criteo_x4_001中，按照Running steps做出的结果是
> "data_format": "csv",
> "dataset_id": "criteo_x4_9ea3bdfc",
> "model_id": "DCN_criteo_x4_012_dc8ab363",
> "model_root": "./Criteo/DCN_criteo_x4_001/",
> 最终结果 logloss:0.437622 - AUC:0.814319
> ```
> 
> 
>      
>   
> 
> 
> 请问这个结果是你自己重新跑的？

————————————————————————————————————————————————————
您好，是的，这个结果是我按照README中Running steps 自己跑出的结果。
我的硬件环境为：
GPU: Tesla P40 22G
RAM: 125G

**Comment by zhujiem** [comment]
使用GPU训练会导致一些硬件相关的随机性，可能与cuda版本相关。所以在环境里我列出了硬件及cuda版本。总的来说，Criteo数据集上几个万分点的波动都是正常的，效果还算稳定。其他小的数据集波动更大，波动可能到千分位。

**Comment by zhujiem** [comment]
一般AUC_diff<0.001 其实已经算精准复现了
