### ISSUE TITLE
关于 model_config.yaml 中的模型后缀

### ISSUE THREAD

**Issue by ententent** [openbenchmark/BARS#23]
感谢作者建立并开源了BARS项目，是 CTR prediction 领域巨人的肩膀

在 [model_config.yaml](https://github.com/openbenchmark/BARS/blob/main/ctr_prediction/benchmarks/DIN/DIN_taobaoad_x1/DIN_taobaoad_x1_tuner_config_07/model_config.yaml) 中会有多个模型配置，如：
- DIN_taobaoad_x1_001_6c779213
- DIN_taobaoad_x1_002_5f3df4a0
- ...
- DIN_taobaoad_x1_012_13c23a36

请问这里的八位数字/字母组合得到的后缀，有什么含意吗？以及他们是怎么生成的

感谢~！

**Comment by zhujiem** [comment]
感谢您对BARS项目的认可。

多个模型配置是参数grid search遍历生成的，001、002...表示生成的第几组参数配置。后面的hash_id是用于区分不同模型配置，将配置str直接hash得到，没有实际意义。
