### ISSUE TITLE
Autoint+ cant't eproducible using  KKBox_x1 config

### ISSUE THREAD

**Issue by lsquser** [openbenchmark/BARS#9]
I want to reproduct AutoInt+ with KKBox config,here https://github.com/openbenchmark/BARS/blob/master/ctr_prediction/benchmarks/AutoInt/AutoInt%2B_kkbox_x1/AutoInt%2B_kkbox_x1_tuner_config_06.yaml .but i can't get the result logloss: 0.476795 - AUC: 0.852967.myr result is here 
![捕获](https://user-images.githubusercontent.com/49977462/156083529-2b07e2e9-4933-4868-931b-e239c5cef007.JPG).
My config is 
![config](https://user-images.githubusercontent.com/49977462/156083866-cad490ca-679a-4033-b916-f33e6f5dc267.JPG)

**Comment by lsquser** [comment]
@zhujiem

**Comment by xpai** [comment]
The reproducing steps have been updated. The environment is import to reproduce the results.

**Comment by xpai** [comment]
@lsquser  Hi, could you help test whether  you can reproduce the results following the new guide? https://github.com/openbenchmark/BARS/tree/master/ctr_prediction/benchmarks/AutoInt/AutoInt%2B_kkbox_x1

**Comment by lsquser** [comment]
OK i'm testing,but my GPU server busy for several program.Please wait patiently until running the AutoInt test




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openbenchmark/BARS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月17日(星期四) 下午5:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openbenchmark/BARS] Autoint+ cant't eproducible using  KKBox_x1 config (Issue #9)





 
@lsquser  Hi, could you help test whether  you can reproduce the results following the new guide? https://github.com/openbenchmark/BARS/tree/master/ctr_prediction/benchmarks/AutoInt/AutoInt%2B_kkbox_x1
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lsquser** [comment]
I hava get the result which be added as an attachment
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openbenchmark/BARS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月17日(星期四) 下午5:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openbenchmark/BARS] Autoint+ cant't eproducible using  KKBox_x1 config (Issue #9)





 
@lsquser  Hi, could you help test whether  you can reproduce the results following the new guide? https://github.com/openbenchmark/BARS/tree/master/ctr_prediction/benchmarks/AutoInt/AutoInt%2B_kkbox_x1
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xpai** [comment]
Hi, The attachment seems not available.

**Comment by lsquser** [comment]
I have sent the contents of the result file.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openbenchmark/BARS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月18日(星期五) 上午10:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openbenchmark/BARS] Autoint+ cant't eproducible using  KKBox_x1 config (Issue #9)





 
Hi, The attachment seems not available.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xpai** [comment]
The email content is not shown on Github.

**Comment by lsquser** [comment]
[AutoInt_kkbox_x1_tuner_config_06.csv](https://github.com/openbenchmark/BARS/files/8301473/AutoInt_kkbox_x1_tuner_config_06.csv)

**Comment by lsquser** [comment]
I'm sorry for the long delay.

**Comment by xpai** [comment]
[test] logloss: 0.478361 - AUC: 0.852984

The result (diff < 0.001) is deemed consistent. Thanks!

**Comment by lsquser** [comment]
The environment is as shown above
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openbenchmark/BARS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月18日(星期五) 上午10:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openbenchmark/BARS] Autoint+ cant't eproducible using  KKBox_x1 config (Issue #9)





 
Hi, The attachment seems not available.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhujiem** [comment]
What's the problem?
